# Generated by Django 4.0.6 on 2022-07-27 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FuelSite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='stAddress2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
