# Generated by Django 4.0.6 on 2022-08-01 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FuelSite', '0002_alter_client_staddress2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=15),
        ),
    ]
