# Generated by Django 4.0.6 on 2022-07-23 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FuelSite', '0002_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=15),
        ),
    ]
