# Generated by Django 4.0.6 on 2022-07-11 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='fuelQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gallonsRequested', models.IntegerField()),
                ('deliveryDate', models.DateField()),
                ('deliveryAddress', models.CharField(max_length=100)),
                ('suggestedPrice', models.DecimalField(decimal_places=2, max_digits=100)),
                ('totalAmountDue', models.DecimalField(decimal_places=2, max_digits=100)),
            ],
        ),
    ]
